version: 2.1
orbs:
  maven: circleci/maven@0.0.12
workflows:
  maven_test:
    jobs:
      - build
      - maven/test # checkout, build, test, and upload test results
jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps: